### ISSUE TITLE
Issue with relative date when it happens on the first of the month.

### ISSUE THREAD

**Issue by gbpnkans** [sonirico/datetoken.js#279]
var tokenToDate = require('datetoken/utils').tokenToDate;

//For last month from 6/5/2021
console.log(tokenToDate('now-1M/M',new Date('2021-06-05')) );
console.log(tokenToDate('now-1M@M',new Date('2021-06-05')) );

//For last month from 6/1/2021 - INCORRECT
console.log(tokenToDate('now-1M/M',new Date('2021-06-01')) );
console.log(tokenToDate('now-1M@M',new Date('2021-06-01')) );

**Comment by sonirico** [comment]
Hi @gbpnkans  for opening an issue. Would you care to state what should be the output according to your expectations?

My output is the following and I consider it to be ok:

```
> var tokenToDate = require('datetoken/utils').tokenToDate;
undefined
>
> //For last month from 6/5/2021
undefined
> console.log(tokenToDate('now-1M/M',new Date('2021-06-05')) );
2021-05-01T00:00:00.000Z
undefined
> console.log(tokenToDate('now-1M@M',new Date('2021-06-05')) );
2021-05-31T23:59:59.999Z
undefined
>
> //For last month from 6/1/2021 - INCORRECT
undefined
> console.log(tokenToDate('now-1M/M',new Date('2021-06-01')) );
2021-05-01T00:00:00.000Z
undefined
> console.log(tokenToDate('now-1M@M',new Date('2021-06-01')) );
2021-05-31T23:59:59.999Z
undefined
>
```

**Comment by gbpnkans** [comment]
```
$ node
Welcome to Node.js v14.16.0.
Type ".help" for more information.
> var tokenToDate = require('datetoken/utils').tokenToDate;
undefined
> console.log(tokenToDate('now-1M/M',new Date('2021-06-05')) );
2021-05-01T06:00:00.000Z
undefined
> console.log(tokenToDate('now-1M@M',new Date('2021-06-05')) );
2021-06-01T05:59:59.999Z
undefined
> console.log(tokenToDate('now-1M/M',new Date('2021-06-01')) );
**2021-04-01T06:00:00.000Z**
undefined
> console.log(tokenToDate('now-1M@M',new Date('2021-06-01')) );
**2021-05-01T05:59:59.999Z**
undefined
> 
```

I do see an issue with the timezone causing issues. But 04/01 does not make sense.

**Comment by sonirico** [comment]
That's clearly a timezone issue. Typically when running node applications, I tend to start the interpreter like this in both production and development environments (event on docker or similar):

`TZ=UTC node` 

In order to prevent node to pick up my machine's local timezone. 

Either way, I agree that `tokenToDate` should accept a third optional parameter indicating the timezone, but in server side applications do not really made much sense unless for simulation purposes, and in the frontend the dependency employed by datetoken to calculate dates (which is [date-fns](https://date-fns.org/)) automatically handles this by reading the [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) interface.

**Comment by gbpnkans** [comment]
If I have TZ=UTC then it fixes issue. A third parameter will really help. Result is way different than the timezone offset.

$TZ=UTC node dt.js
2021-05-01T00:00:00.000Z
2021-05-31T23:59:59.999Z
2021-05-01T00:00:00.000Z
2021-05-31T23:59:59.999Z
pi@kanspi:~/nodetest $ node dt.js
2021-04-30T23:00:00.000Z
2021-05-31T22:59:59.999Z
2021-04-30T23:00:00.000Z
2021-05-31T22:59:59.999Z
